### ISSUE TITLE
Execution error (IllegalStateException): session closed

### ISSUE THREAD

**Issue by farcaller** [protojure/lib#169]
I have a pretty straightforward client setup:

```clj
(defonce client @(grpc.http2/connect {:uri "http://localhost:8080"}))
```

Calling a method on this client works fine, however, after some time, I start getting errors:

```clj
[nREPL-session-2e8a6856-3d0e-4269-a61e-2f7be41bc856] ERROR protojure.internal.grpc.client.providers.http2.core - GRPC failed: #error {
 :cause session closed
 :via
 [{:type java.lang.IllegalStateException
   :message session closed
   :at [org.eclipse.jetty.http2.HTTP2Session$StreamsState reserveSlot HTTP2Session.java 2255]}]
 :trace
...
Execution error (IllegalStateException) at org.eclipse.jetty.http2.HTTP2Session$StreamsState/reserveSlot (HTTP2Session.java:2255).
```

Am I missing something? I'd have expected that the grpc client would reconnect on its own, if needed.

**Comment by ghaskins** [comment]
Ah, I think there is an idle-timeout by default.  There is a way to disable that if you want to leave long-running connections.  Let me look it up and get back to you

**Comment by ghaskins** [comment]
https://github.com/protojure/lib/blob/db291b4df70395c7ce3a2b480e58ca15518234fb/test/test/protojure/grpc_test.clj#L716

You want to set :idle-timeout to -1 to disable the timeout feature.

**Comment by farcaller** [comment]
Thanks, that fixes the client-side issue!

Granted, restarting a server breaks the connection too so it seems the clojure client has to be be coded more defensively than the other language implementations (the grpc-core one reconnects on its own).
