### ISSUE TITLE
protojure client does not handle google.protobuf.Empty or not tag message as response correctly

### ISSUE THREAD

**Issue by Rkiouak** [protojure/lib#33]
Observed client decode error on a response from a service like:

```
service doRPC{
  rpc doRPCt(google.protobuf.Empty) returns (google.protobuf.Empty);
}
```

Suspect the protojure client can not handle a response consisting of a message with no tags

**Comment by ghaskins** [comment]
I believe this now works properly as of v1.5.1 because of https://github.com/protojure/lib/commit/d6ad80c8a893aaa75eefeb5c751207795d4565f2
