### ISSUE TITLE
compilation error when combined with clojure.data.priority-map

### ISSUE THREAD

**Issue by tuddman** [protojure/lib#48]
Hello,

I was wondering if you might be able to shine any light on why including `protojure "1.5.1"` as a dependency into an existing project would cause the compilation error explained [here](https://github.com/tuddman/priority-map-test/issues/1).

Specifically on not honoring the exclusion of `subseq` in a namespace.

I've created the simplest [repo](https://github.com/tuddman/priority-map-test) to reproduce the error.

I suspect one-or-more of the pedestal dependent libraries may be the culprit, but I haven't been able to reproduce the error with 'just' a `pedestal` app + `clojure.data.priority-map`; it is only when depending on `protojure`

`[io.pedestal/pedestal.service "0.5.7"]` pulls in `clojure.data.priority-map "0.0.7"` ...

very strange.

**Comment by ghaskins** [comment]
@tuddman thanks for the report.  I'm not sure what might be causing that, but ill take a look.

**Comment by ghaskins** [comment]
Thanks for the great reproduction case.  I pulled it down and was able to reproduce the issue you describe.  I also agree its not clear what the problem is.  I was thinking there may be some kind of dep conflict that an exclusion might fix, but nothing was obvious.

My biggest suspicion is with the really old promesa lib (v3.0.0) we are using.  Ill keep digging.

**Comment by ghaskins** [comment]
Even after upgrading everything to the latest, the problem persists.  This is a strange one.

**Comment by tuddman** [comment]
hmm.. perhaps one of these:

```
$ lein pom
Wrote /home/tuddman/code/libraries/priority-map-test/pom.xml
$ mvn dependency:tree -Dverbose=true
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< priority-map-test:priority-map-test >-----------------
[INFO] Building priority-map-test 0.1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ priority-map-test ---
[INFO] priority-map-test:priority-map-test:jar:0.1.0-SNAPSHOT
[INFO] +- org.clojure:clojure:jar:1.10.1:compile
[INFO] |  +- org.clojure:spec.alpha:jar:0.2.176:compile
[INFO] |  \- org.clojure:core.specs.alpha:jar:0.2.44:compile
[INFO] +- protojure:protojure:jar:1.5.1:compile
[INFO] |  +- org.clojure:tools.logging:jar:1.0.0:compile
[INFO] |  |  \- (org.clojure:clojure:jar:1.4.0:compile - omitted for conflict with 1.10.1)
[INFO] |  +- org.apache.commons:commons-compress:jar:1.20:compile
[INFO] |  +- commons-io:commons-io:jar:2.6:compile
[INFO] |  +- funcool:promesa:jar:3.0.0:compile
[INFO] |  \- lambdaisland:uri:jar:1.2.1:compile
[INFO] |     \- (org.clojure:clojure:jar:1.10.1:compile - omitted for duplicate)
[INFO] \- org.clojure:data.priority-map:jar:1.0.0:compile
[INFO]    \- (org.clojure:clojure:jar:1.5.1:compile - omitted for conflict with 1.10.1)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.296 s
[INFO] Finished at: 2020-04-20T20:54:27-06:00
[INFO] ------------------------------------------------------------------------
```

I initially thought it may be `pedestal-service` as including that dependency .. and `lein clean && lein deps` would pull `clojure.data.priority-map "0.0.7"`   after deleting my `~/.m2/repository/org/clojure/data/priority-map/*`

but no :/  same issue persists.

**Comment by ghaskins** [comment]
Yeah, I also tried loading all the deps explicitly without protojure enabled so I could go one by one and find the culprit...but no dice.  Its a head-scratcher.

**Comment by tuddman** [comment]
is this something @Engelberg or @puredanger may be able to recognize more easily?  It seems one library is running interference on another.  But which, how, and where?  Any insights or comments are much appreciated!

**Comment by puredanger** [comment]
protojure 1.5.1 depends (indirectly) on an older version of data.priority-map (0.0.7) that did not have subseq. You should be able to add an exclusion to protojure to avoid that.

protojure 1.5.1 -> core.async 1.1.587 -> tools.analyzer.jvm 1.0.0 -> core.memoize 0.8.2 -> core.cache 0.8.2 -> data.priority-map 0.0.7

**Comment by puredanger** [comment]
there are also newer versions of core.memoize and core.cache that depend on data.priority-map 1.0.0 but I don't think there's a newer version of tools.analyzer.jvm using them yet.

**Comment by tuddman** [comment]
thanks @puredanger!   out of interest, what tool(s) or commands allowed you to get to that?  `lein deps :tree` didn't show full depth when I tried. 

I set
```
:dependencies [... [protojure "1.5.1" :exclusions [[org.clojure/data.priority-map]]]]
```
and then `rm -rf ~/.m2/repository/org/clojure/data.priority-map/* &&  lein clean && lein deps && lein repl`    but the issue persists.

Am I doing sth wrong as it relates to setting the `:exclusions ...` ?

**Comment by puredanger** [comment]
I used `clj -Sdeps '{:deps {protojure/protojure {:mvn/version "1.5.1"}}}' -Stree`

**Comment by puredanger** [comment]
Note that lein (via pomegranate) and clj have different version selection algorithms, so this info is only relevant with some interpretation, it was just easier for me to test. Your exclusions look right to me. I don't really understand why lein is not getting the desired version here. I would expect your use of priority-map at the top level to take priority for lein/mvn (same for clj).

You should look at the actual path you're getting from `lein classpath`.

**Comment by ghaskins** [comment]
Thanks for both helping and for teaching me that method of dep spelunking @puredanger

**Comment by tuddman** [comment]
@puredanger thank you for bumping the deps in `tools.analyzer.jvm`

Including `:exclusions [...]` hasn't solve this.

Not sure if relevant, but I've now read other GH [issue](https://github.com/ptaoussanis/timbre/issues/263) threads with similar issues with AOT-compiled deps leading to  compilation error ~
```
#error {
 :cause _____ does not exist
...
```

the [core.async deps.edn](https://github.com/clojure/core.async/blob/master/deps.edn#L3) points to `[tools.analyzer.jvm 1.0.0]`  , but the [tools.anayzer.jvm project.clj](https://github.com/clojure/tools.analyzer.jvm/blob/master/project.clj#L1) still points to pre-1.x.x (`0.7.3-SNAPSHOT`)

does a `1.0.1` release of `tools.analyzer.jvm` need to be cut to break the chain of pointing to the old?

**Comment by puredanger** [comment]
Looking at this again, the problem is that protojure is AOT compiled and includes classes from many of its deps, which is bad, and you shouldn't do that, for multiple reasons. The main reason you see here is that you've effectively caused multiple versions of the dep to occur in the classpath - a visible one in source form based on the data.priority-map version, and an invisible compiled one baked into the protojure jar. And the latter one will take priority.

This will cause problems for anyone that uses protojure in combination with other libs and takes all the control out of the hands of the library user. If you're going to AOT compile, please filter down to just classes in your library. (I don't how to do that with Leiningen, but I'm sure there is some way to do it.)

Really, I would encourage you to not AOT at all and instead provide libraries in source form. AOT-ing takes a different kind of control away from users, which is the choice of which Clojure version and flags to use when compiling (like direct linking).

**Comment by ghaskins** [comment]
@puredanger thanks for pointing that out.  It wasn't a conscious decision to AOT compile per se.  I probably either blindly accepted a lein-template default or carried it over from an uberjar executable when I split the library out.  To be honest, I wasn't aware of the implication you pointed out either, so thank you for that.  I'll PR this to just build source, as I agree that makes sense.

**Comment by ghaskins** [comment]
Just looked, and I see I am explicitly AOT compiling some gen-class stuff.  I don't recall what I encountered when I thought I needed that, but hopefully that is no longer the case and can be removed.

**Comment by ghaskins** [comment]
I just tried it without them and ran into what likely prompted me to go down the AOT path to begin with:

compilation of the protojure-lib itself now fails with:

```
Caused by: java.lang.ClassNotFoundException: protojure.internal.grpc.io.InputStream
```

Im guessing because of my gen-class usage, such as here: https://github.com/protojure/lib/blob/master/src/protojure/internal/pedestal/io.clj#L8

Guidance appreciated.

**Comment by puredanger** [comment]
If you need it for gen-class, that's fine, just don't ship the lib with all the transitively compiled classes in it, filter down to just the classes from this lib. I think you can do that with leiningen, but I'm up to date on how.

**Comment by tuddman** [comment]
in the spirit of stripping down to _only what's needed_
Greg - might it be simpler to remove leiningen entirely from this lib as it is itself _just a dependency_, albeit a normally very useful one?     
Alex - off the top of your head, do you know of other lib(s) that are doing something similar to protojure, but are built w/out leiningen?       

I've already learned some things from this issue, and will happily learn more from other examples if I can.

**Comment by puredanger** [comment]
Off the top of my head, no, sorry. Most Clojure libs are source only and I don't have a good example in mind.

**Comment by tuddman** [comment]
closing.  Issue is resolved with updated dependencies.
