### ISSUE TITLE
Error trying out demo-server

### ISSUE THREAD

**Issue by kevolson** [protojure/lib#56]
When trying this

```
lein new protojure demo-server
cd demo-server && make all
lein run
```

I received 

```
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/ec2-user/.m2/repository/com/fzakaria/slf4j-timbre/0.3.17/slf4j-timbre-0.3.17.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/ec2-user/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [com.github.fzakaria.slf4j.timbre.TimbreLoggerFactory]
Reflection warning, protojure/grpc/codec/lpm.clj:170:5 - reference to field close can't be resolved.
Syntax error (IllegalArgumentException) compiling . at (protojure/protobuf/serdes/core.clj:80:14).
No matching method getTagWireType found taking 1 args for class com.google.protobuf.WireFormat

Full report at:
/tmp/clojure-1189555812035203599.edn
```
Am I doing something wrong?

Thanks

[clojure-1189555812035203599.edn.txt](https://github.com/protojure/lib/files/5092416/clojure-1189555812035203599.edn.txt)

**Comment by mvarela** [comment]
Which Java version are you using? I just tried with OpenJDK 8 and 11, and couldn't reproduce your error.

**Comment by kevolson** [comment]
14, I'll try a different version

`
$ java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment 20.3 (build 14.0.1+7)
OpenJDK 64-Bit Server VM 20.3 (build 14.0.1+7, mixed mode, sharing)
`

**Comment by kevolson** [comment]
I was able to get it started (even in Java 14) by upgrading lein-cljfmt to 0.7.0..  I have a reference to lein-cljfmt in my ~/.lein/profiles.clj file.  Not sure why that fixed it.  

Side note: I am now getting a bunch of "An illegal reflective access operation has occurred" errors on server startup but I suspect that is a different issue so will close this one.
