### ISSUE TITLE
logging exceptions

### ISSUE THREAD

**Issue by souenzzo** [protojure/lib#83]
In many places, exceptions are logged as text/values

https://github.com/protojure/lib/blob/master/src/protojure/pedestal/core.clj#L320
https://github.com/protojure/lib/blob/master/src/protojure/pedestal/core.clj#L156
https://github.com/protojure/lib/blob/master/src/protojure/pedestal/core.clj#L294

All this points could use `(log/error :exception ex)`. It would allow proper formatting on custom formaters. 
On L156 it could be `(log/error :msg "close-output-channel" :exception ex)`

It can also be used in `log/info` and any other pedestal log. 

From `io.pedestal.log` API DOCS
http://pedestal.io/api/pedestal.log/io.pedestal.log.html#var-log
```
 :exception -- A Throwable/Exception to log
```

can I make a pull request?

**Comment by ghaskins** [comment]
> can I make a pull request?

Of course.  You will just need a DCO "Signed-off-by" in your commit header, and also please add yourself to the CONTRIBUTORS.  Thank you!
