### ISSUE TITLE
No matching method getTagWireType found taking 1 args

### ISSUE THREAD

**Issue by tuddman** [protojure/lib#93]
Interested in solving for the last two lines, though the first two are sill there and worth pointing out: 

```
Reflection warning, protojure/pedestal/core.clj:242:3 - reference to field getPeerAddress can't be resolved.
Reflection warning, protojure/grpc/codec/lpm.clj:171:5 - reference to field close can't be resolved.
Syntax error (IllegalArgumentException) compiling . at (protojure/protobuf/serdes/core.clj:80:14).
No matching method getTagWireType found taking 1 args for class com.google.protobuf.WireFormat
```

[culprit line](https://github.com/protojure/lib/blob/master/src/protojure/protobuf/serdes/core.clj#L80)

except [this JavaDoc](https://developers.google.com/protocol-buffers/docs/reference/java) shows the `getWireType` function very much takes one arg, `int tag`

using deps: 

```
 [protojure "1.6.1"]
 [protojure/google.protobuf "0.9.1"]
```

google.protobuf is using `0.3.11` of protobuf-java.  `3.18.0` & `4.0.0-RC` is available:

 https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java

from https://github.com/protojure/google.protobuf/blob/master/project.clj#L10    which is two years out of date now.

Need to still confirm if updating locally fixes this issue.

**Comment by tuddman** [comment]
yep.  and of course updating the dependent google.protobuf-java library to the latest, `3.18.0` in protojure/google.protobuf and `lein install` and then building dep locally, works. :)   which is the version referenced in above javadocs.

```
 [protojure/google.protobuf "0.9.2-SNAPSHOT"]    <-installed locally, with updated version of protobuf-java
```

if anyone else runs into this, update your dependencies.

**Comment by tuddman** [comment]
Would it possible to update google.protobuf-java libraries to the latest:  currently `3.18.0`

and mint a release into clojars.

this `lib` is using `3.17.3`:   https://github.com/protojure/lib/blob/master/project.clj#L15

the `protoc-plugin` is using `3.14.0`: https://github.com/protojure/protoc-plugin/blob/master/project.clj#L17

and `google.protobuf` is using `3.11.1` : https://github.com/protojure/google.protobuf/blob/master/project.clj#L10


cc @ghaskins  thanks again for a great clojure library!

**Comment by ghaskins** [comment]
Ill try to update these this weekend.  Thanks for the report

**Comment by ghaskins** [comment]
https://github.com/protojure/google.protobuf/pull/4

**Comment by tuddman** [comment]
works with the latest release of `google.protobuf`, `1.0.0`.   Thanks, @ghaskins et al.!!
